spring:
  application:
    name: check-test
  cloud:
    consul:
#      host: localhost
      host: 192.168.50.191
      discovery:
        health-check-path: /check
        health-check-interval: 5s
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

server:
  port: 8088
